spring:
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: weather-stream-processor
  json:
    use.type.headers: false
    value.default.type: java.lang.String

app:
  source-topic-name: weather-publisher-data
  source-destination-stream-map: '{
    "city_attributes": "weather-data-city-attributes",
    "humidity": "weather-data-humidity",
    "pressure": "weather-data-pressure",
    "temperature": "weather-data-temperature",
    "weather_description": "weather-data-description",
    "wind_direction": "weather-data-wind-direction",
    "wind_speed": "weather-data-wind-speed"
  }'